CREATE TABLE IF NOT EXISTS wines (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    image VARCHAR(255) NOT NULL,
    description TEXT,
    avis TEXT
);

INSERT INTO wines (name, price, image, description) VALUES
('Château Margaux', 250.00, 'wine1.png', 'Un vin rouge iconique de Bordeaux, d''une finesse et élégance remarquables. Arômes de fruits rouges, cassis et notes florales.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Cabernet Sauvignon majoritaire, Merlot\n\n**Région :** Margaux, Bordeaux, France\n\n**Accords Mets & Vins :** Agneau, bœuf rôti, fromages affinés\n\n**Potentiel de garde :** 30-60 ans et plus\n\n\n'),
('Beaujolais-Villages', 25.00, 'wine2.png', 'Le **Beaujolais-Villages** est un vin rouge charmant et accessible, provenant du cœur du Beaujolais. Élaboré à partir du cépage Gamay, il se distingue par ses **arômes vifs de fruits rouges frais** et une belle vivacité. Il est parfait pour une dégustation décontractée.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Gamay\n\n**Région :** Beaujolais, France\n\n**Accords Mets & Vins :** Charcuterie fine, salades composées, volailles grillées, fromages frais\n\n**Potentiel de garde :** 2-5 ans\n\n\n'),
('Côtes du Rhône', 35.00, 'wine3.png', 'Le **Côtes du Rhône** est un vin rouge polyvalent et généreux de la Vallée du Rhône. Issu d''un assemblage de cépages typiques, il offre un **profil aromatique riche** de fruits rouges mûrs et d''épices. Sa **structure équilibrée** et ses tanins souples en font un excellent compagnon de table.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Grenache, Syrah, Mourvèdre (et autres cépages locaux)\n\n**Région :** Vallée du Rhône, France\n\n**Accords Mets & Vins :** Viandes rouges grillées, plats en sauce méditerranéens, gibiers légers, fromages affinés\n\n**Potentiel de garde :** 5-10 ans\n\n\n'),
('Sassicaia', 200.00, 'wine4.png', 'Le Sassicaia est un vin rouge italien emblématique de Toscane, souvent considéré comme le premier **Super Tuscan**. Il se distingue par sa **structure élégante**, ses **tanins soyeux** et ses **arômes complexes** de fruits noirs mûrs et d''épices.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Cabernet Sauvignon, Cabernet Franc\n\n**Région :** Bolgheri, Toscane, Italie\n\n**Accords Mets & Vins :** Viandes rouges, gibiers, fromages affinés\n\n**Potentiel de garde :** 15-30 ans\n\n\n'),
('Opus One', 320.00, 'wine5.png', 'Né de la collaboration légendaire entre **Baron Philippe de Rothschild** et **Robert Mondavi**, Opus One est un vin emblématique de Napa Valley, en Californie. Il offre un profil aromatique riche avec des notes de **fruits noirs mûrs, de cèdre et de nuances épicées**.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Cabernet Sauvignon dominant, Merlot, Cabernet Franc, Petit Verdot\n\n**Région :** Napa Valley, Californie, USA\n\n**Accords Mets & Vins :** Bœuf grillé, agneau, fromages intenses\n\n**Potentiel de garde :** 20-40 ans\n\n\n'),
('Château d''Yquem', 400.00, 'wine6.png', 'Le Château d''Yquem est le plus célèbre des vins liquoreux de Bordeaux, un Premier Cru Supérieur de Sauternes. Produit à partir de raisins botrytisés, il est d''une **complexité et d''une richesse inégalées** avec des arômes enivrants de **miel, d''abricot confit et de fleurs blanches**.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Sémillon, Sauvignon Blanc\n\n**Région :** Sauternes, Bordeaux, France\n\n**Accords Mets & Vins :** Foie gras, desserts aux fruits, fromages bleus\n\n**Potentiel de garde :** 50-100 ans et plus\n\n\n'),
('Vega Sicilia Unico', 450.00, 'wine7.png', 'Le Vega Sicilia Unico est l''un des vins les plus emblématiques d''Espagne. Élaboré principalement à partir de Tempranillo, il présente des arômes intenses de fruits rouges confiturés, de cuir, de tabac et de cèdre. Un vin de collection qui peut vieillir des décennies.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Tempranillo, Cabernet Sauvignon\n\n**Région :** Ribera del Duero, Espagne\n\n**Accords Mets & Vins :** Agneau rôti, gibiers, jambon ibérique\n\n**Potentiel de garde :** 30-60 ans et plus\n\n\n'),
('Gaja Barbaresco', 280.00, 'wine9.png', 'Le Gaja Barbaresco est une icône des vins du Piémont en Italie, élaboré à partir du cépage Nebbiolo. Célèbre pour son **élégance, sa finesse et sa structure tannique raffinée**. Il dégage des arômes complexes de **rose, de cerise, de truffe et de goudron**.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Nebbiolo\n\n**Région :** Barbaresco, Piémont, Italie\n\n**Accords Mets & Vins :** Plats à base de truffe, viandes braisées, fromages matures\n\n**Potentiel de garde :** 20-40 ans\n\n\n'),
('Egon Müller Scharzhofberger Riesling Auslese', 700.00, 'wine10.png', 'L''Egon Müller Scharzhofberger Riesling Auslese est l''un des plus grands vins doux du monde. Exemple sublime de l''équilibre entre le **sucre résiduel, l''acidité tranchante et une minéralité prononcée**, avec des arômes de **pêche, d''abricot et de miel**.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Riesling\n\n**Région :** Moselle, Allemagne\n\n**Accords Mets & Vins :** Foie gras, desserts fruités, fromages bleus\n\n**Potentiel de garde :** 50-100 ans et plus\n\n\n'),
('Henschke Hill of Grace', 600.00, 'wine8.png', 'Le Henschke Hill of Grace est un Shiraz australien légendaire, issu de vignes pré-phylloxériques. Il se caractérise par sa **profondeur de couleur** et ses **arômes intenses de mûre, de réglisse et de poivre noir**.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Shiraz\n\n**Région :** Eden Valley, Australie du Sud\n\n**Accords Mets & Vins :** Bœuf, gibier, plats épicés\n\n**Potentiel de garde :** 20-50 ans et plus\n\n\n'),
('Ridge Monte Bello', 220.00, 'wine11.png', 'Le Ridge Monte Bello est un vin californien de légende, produit dans les montagnes de Santa Cruz. Réputé pour son **style classique et sa capacité de vieillissement exceptionnelle**, il offre des arômes complexes de **cassis, de mûre, de menthe et de tabac**.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Cabernet Sauvignon dominant, Merlot, Petit Verdot, Cabernet Franc\n\n**Région :** Santa Cruz Mountains, Californie, USA\n\n**Accords Mets & Vins :** Bœuf Wellington, agneau rôti, gibier\n\n**Potentiel de garde :** 20-50 ans\n\n\n'),
('Chablis Grand Cru', 180.00, 'wine12.png', 'Un Chablis Grand Cru de Bourgogne, expression pure du Chardonnay sur sol kimméridgien. Fraîcheur et minéralité exceptionnelles.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Chardonnay\n\n**Région :** Chablis, Bourgogne, France\n\n**Accords Mets & Vins :** Fruits de mer, huîtres, poissons nobles, fromages de chèvre\n\n**Potentiel de garde :** 10-25 ans\n\n\n'),
('Gevrey-Chambertin Premier Cru', 280.00, 'wine13.png', 'Un Premier Cru de Gevrey-Chambertin, vin rouge emblématique de la Bourgogne. Élégance, structure et arômes de cerise et sous-bois.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Pinot Noir\n\n**Région :** Gevrey-Chambertin, Bourgogne, France\n\n**Accords Mets & Vins :** Bœuf bourguignon, gibier à plumes, fromages de caractère\n\n**Potentiel de garde :** 15-30 ans\n\n\n'),
('Meursault Premier Cru', 220.00, 'wine14.png', 'Un Meursault Premier Cru, vin blanc opulent et complexe de Bourgogne. Notes de noisette grillée, beurre frais et fleurs blanches.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Chardonnay\n\n**Région :** Meursault, Bourgogne, France\n\n**Accords Mets & Vins :** Poissons en sauce, volailles à la crème, fromages de type Comté\n\n**Potentiel de garde :** 10-25 ans\n\n\n'),
('Volnay Premier Cru', 195.00, 'wine15.png', 'Un Volnay Premier Cru, vin rouge de Bourgogne connu pour sa finesse et son élégance. Arômes délicats de fruits rouges et notes florales.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Pinot Noir\n\n**Région :** Volnay, Bourgogne, France\n\n**Accords Mets & Vins :** Pintade rôtie, veau, fromages doux\n\n**Potentiel de garde :** 10-20 ans\n\n\n'),
('Puligny-Montrachet Premier Cru', 310.00, 'wine16.png', 'Un Puligny-Montrachet Premier Cru, l''un des Chardonnay les plus prestigieux de Bourgogne. Minéralité, complexité et pureté.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Chardonnay\n\n**Région :** Puligny-Montrachet, Bourgogne, France\n\n**Accords Mets & Vins :** Homard, Saint-Jacques, volaille de Bresse\n\n**Potentiel de garde :** 15-30 ans\n\n\n'),
('Mâcon-Villages', 35.00, 'wine17.png', 'Un Mâcon-Villages, vin blanc frais et fruité de Bourgogne. Idéal pour une dégustation spontanée, avec des notes d''agrumes et de fleurs blanches.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Chardonnay\n\n**Région :** Mâconnais, Bourgogne, France\n\n**Accords Mets & Vins :** Apéritif, salades composées, poissons grillés\n\n**Potentiel de garde :** 3-5 ans\n\n\n'),
('Crémant de Bourgogne Brut', 28.00, 'wine18.png', 'Un Crémant de Bourgogne Brut, vin effervescent élégant et festif. Bulles fines, arômes de fruits blancs et touche briochée.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Pinot Noir, Chardonnay, Gamay, Aligoté\n\n**Région :** Bourgogne, France\n\n**Accords Mets & Vins :** Apéritif, sushis, desserts aux fruits\n\n**Potentiel de garde :** 2-4 ans\n\n\n'),
('Arbois Pupillin Ploussard', 45.00, 'wine19.png', 'Un vin rouge léger et fruité du Jura, élaboré à partir du cépage Ploussard. Notes de fruits rouges croquants et une belle fraîcheur.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Ploussard\n\n**Région :** Arbois Pupillin, Jura, France\n\n**Accords Mets & Vins :** Charcuterie, quiches, volailles\n\n**Potentiel de garde :** 5-10 ans\n\n\n'),
('Côtes du Jura Savagnin', 55.00, 'wine20.png', 'Un vin blanc typique du Jura, issu du cépage Savagnin. Style oxydatif unique avec des arômes de noix, pomme verte et épices.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Savagnin\n\n**Région :** Côtes du Jura, Jura, France\n\n**Accords Mets & Vins :** Comté, volaille à la crème, cuisine asiatique\n\n**Potentiel de garde :** 10-30 ans\n\n\n'),
('Pommard Premier Cru', 260.00, 'wine21.png', 'Un Pommard Premier Cru, vin rouge de Bourgogne réputé pour sa puissance et sa structure. Arômes intenses de fruits noirs et tanins fermes.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Pinot Noir\n\n**Région :** Pommard, Bourgogne, France\n\n**Accords Mets & Vins :** Bœuf, gibier, fromages de vache affinés\n\n**Potentiel de garde :** 15-35 ans\n\n\n'),
('Beaune Premier Cru', 170.00, 'wine22.png', 'Un Beaune Premier Cru, vin rouge élégant de Bourgogne. Un équilibre parfait entre finesse et intensité, avec des notes fruitées et épicées.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Pinot Noir\n\n**Région :** Beaune, Bourgogne, France\n\n**Accords Mets & Vins :** Volaille rôtie, plats végétariens riches, fromages doux\n\n**Potentiel de garde :** 10-25 ans\n\n\n'),
('Pouilly-Fuissé', 65.00, 'wine23.png', 'Un Pouilly-Fuissé, vin blanc du Mâconnais en Bourgogne. Il offre richesse et rondeur, avec des arômes d''amande, de miel et de fleurs blanches.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Chardonnay\n\n**Région :** Pouilly-Fuissé, Bourgogne, France\n\n**Accords Mets & Vins :** Gambas, volailles en sauce, fromages de chèvre\n\n**Potentiel de garde :** 5-15 ans\n\n\n'),
('Veuve Clicquot Brut', 60.00, 'wine24.png', 'Le Veuve Clicquot Brut, un champagne emblématique, est reconnu pour sa puissance aromatique et sa finesse. Bulles fines et persistantes.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Pinot Noir, Pinot Meunier, Chardonnay\n\n**Région :** Champagne, France\n\n**Accords Mets & Vins :** Apéritif, fruits de mer, sushis, volailles rôties\n\n**Potentiel de garde :** 5-10 ans\n\n\n'),
('Château Pichon Longueville Comtesse de Lalande', 380.00, 'wine25.png', 'Un Second Grand Cru Classé de Pauillac, Bordeaux. Puissance et élégance avec des arômes de cassis, cèdre et graphite.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Cabernet Sauvignon dominant, Merlot, Cabernet Franc, Petit Verdot\n\n**Région :** Pauillac, Bordeaux, France\n\n**Accords Mets & Vins :** Agneau, bœuf, gibier, fromages affinés\n\n**Potentiel de garde :** 20-50 ans\n\n\n'),
('Château Cheval Blanc', 600.00, 'wine26.png', 'Un Premier Grand Cru Classé A de Saint-Émilion, Bordeaux. Finesse, complexité et potentiel de vieillissement exceptionnel. Arômes de fruits rouges, réglisse et truffe.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Cabernet Franc, Merlot\n\n**Région :** Saint-Émilion, Bordeaux, France\n\n**Accords Mets & Vins :** Gibiers, viandes rouges nobles, plats truffés\n\n**Potentiel de garde :** 30-70 ans et plus\n\n\n'),
('Sancerre Blanc', 40.00, 'wine27.png', 'Un Sancerre Blanc, vin blanc vif et minéral de la Loire. Arômes intenses d''agrumes, de buis et de pierre à fusil.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Sauvignon Blanc\n\n**Région :** Sancerre, Vallée de la Loire, France\n\n**Accords Mets & Vins :** Fruits de mer, poissons grillés, fromages de chèvre\n\n**Potentiel de garde :** 5-10 ans\n\n\n'),
('Châteauneuf-du-Pape Rouge', 85.00, 'wine28.png', 'Un Châteauneuf-du-Pape Rouge, vin puissant et complexe de la Vallée du Rhône. Arômes de fruits rouges confits, garrigue et épices.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Grenache dominant, Syrah, Mourvèdre (jusqu''à 13 cépages autorisés)\n\n**Région :** Châteauneuf-du-Pape, Vallée du Rhône, France\n\n**Accords Mets & Vins :** Daube de bœuf, gibier, fromages forts\n\n**Potentiel de garde :** 15-30 ans\n\n\n'),
('Alsace Gewürztraminer Grand Cru', 50.00, 'wine29.png', 'Un Gewürztraminer Grand Cru d''Alsace, vin blanc aromatique et exubérant. Notes intenses de litchi, rose et épices douces.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Gewürztraminer\n\n**Région :** Alsace, France\n\n**Accords Mets & Vins :** Cuisine asiatique, plats épicés, fromages bleus\n\n**Potentiel de garde :** 10-20 ans\n\n\n'),
('Rosé de Provence', 30.00, 'wine30.png', 'Un Rosé de Provence, vin frais et élégant, parfait pour les journées ensoleillées. Arômes délicats de fruits rouges et notes florales.\n\n\n\n**Origine et composition** 👇\n\n**Cépage :** Grenache, Cinsault, Syrah, Mourvèdre\n\n**Région :** Provence, France\n\n**Accords Mets & Vins :** Salades, grillades, cuisine méditerranéenne\n\n**Potentiel de garde :** 2-3 ans\n\n\n');


UPDATE wines
SET avis = CASE id
    WHEN 1 THEN 'Exceptionnel ! Une expérience inoubliable, ce Margaux est digne de sa réputation. Profond et élégant, un vin d''une finesse remarquable.'
    WHEN 2 THEN 'Un vin rouge charmant et accessible, parfait pour une dégustation décontractée avec ses arômes vifs de fruits rouges frais.'
    WHEN 3 THEN 'Polyvalent et généreux, ce vin offre un profil aromatique riche de fruits mûrs et d''épices, un excellent compagnon de table.'
    WHEN 4 THEN 'Incroyable ! Un Super Tuscan emblématique, élégant avec des tanins soyeux et des arômes complexes de fruits noirs.'
    WHEN 5 THEN 'Majestueux et puissant, Opus One est un emblème de Napa Valley, riche en notes de fruits noirs mûrs et de cèdre.'
    WHEN 6 THEN 'Divin et d''une richesse inégalée, ce Sauternes est une expérience sensorielle unique, avec des arômes enivrants de miel et d''abricot.'
    WHEN 7 THEN 'Un mythe espagnol, ce Unico est intense avec des arômes de fruits confiturés et de cuir, un vin de collection pour des décennies.'
    WHEN 8 THEN 'Élégant et d''une finesse remarquable, ce Barbaresco est un grand Nebbiolo qui exprime magnifiquement son terroir avec des notes de rose et cerise.'
    WHEN 9 THEN 'Une merveille de Riesling Auslese, offrant un équilibre sublime entre sucre, acidité et minéralité prononcée.'
    WHEN 10 THEN 'Légendaire Shiraz australien, ce vin se distingue par sa profondeur de couleur et ses arômes intenses de mûre et de réglisse.'
    WHEN 11 THEN 'Un classique californien réputé pour son style et sa capacité de vieillissement exceptionnelle, avec des arômes complexes de cassis et de menthe.'
    WHEN 12 THEN 'Expression pure du Chardonnay sur sol kimméridgien, ce Chablis est d''une fraîcheur et minéralité exceptionnelles, parfait avec des fruits de mer.'
    WHEN 13 THEN 'Un emblème de la Bourgogne, ce Premier Cru offre élégance, structure et des arômes sublimes de cerise et de sous-bois.'
    WHEN 14 THEN 'Ce vin blanc opulent et complexe de Bourgogne révèle des notes de noisette grillée, de beurre frais et de fleurs blanches.'
    WHEN 15 THEN 'Connu pour sa finesse et son élégance, ce vin rouge de Bourgogne présente des arômes délicats de fruits rouges et des notes florales.'
    WHEN 16 THEN 'Un des Chardonnay les plus prestigieux de Bourgogne, offrant minéralité, complexité et une pureté exceptionnelle.'
    WHEN 17 THEN 'Frais et fruité, ce vin blanc de Bourgogne est idéal pour une dégustation spontanée, avec des notes d''agrumes et de fleurs blanches.'
    WHEN 18 THEN 'Élégant et festif, ce vin effervescent présente des bulles fines, des arômes de fruits blancs et une touche briochée.'
    WHEN 19 THEN 'Un vin rouge léger et fruité du Jura, avec des notes de fruits rouges croquants et une belle fraîcheur, parfait pour la charcuterie.'
    WHEN 20 THEN 'Typique du Jura, ce vin blanc offre un style oxydatif unique avec des arômes de noix, pomme verte et épices, idéal avec du Comté.'
    WHEN 21 THEN 'Réputé pour sa puissance et sa structure, ce vin rouge de Bourgogne dévoile des arômes intenses de fruits noirs et des tanins fermes.'
    WHEN 22 THEN 'Un vin rouge élégant de Bourgogne, offrant un équilibre parfait entre finesse et intensité, avec des notes fruitées et épicées.'
    WHEN 23 THEN 'Ce vin blanc du Mâconnais offre richesse et rondeur, avec des arômes d''amande, de miel et de fleurs blanches.'
    WHEN 24 THEN 'Un champagne emblématique, reconnu pour sa puissance aromatique et sa finesse, avec des bulles fines et persistantes.'
    WHEN 25 THEN 'Puissance et élégance caractérisent ce Second Grand Cru Classé de Pauillac, avec des arômes de cassis, cèdre et graphite.'
    WHEN 26 THEN 'Un Premier Grand Cru Classé A de Saint-Émilion, offrant finesse, complexité et un potentiel de vieillissement exceptionnel.'
    WHEN 27 THEN 'Vif et minéral, ce Sancerre Blanc de la Loire présente des arômes intenses d''agrumes, de buis et de pierre à fusil.'
    WHEN 28 THEN 'Puissant et complexe, ce vin de la Vallée du Rhône dévoile des arômes de fruits rouges confits, de garrigue et d''épices.'
    WHEN 29 THEN 'Un vin blanc aromatique et exubérant d''Alsace, avec des notes intenses de litchi, de rose et d''épices douces.'
    WHEN 30 THEN 'Frais et élégant, ce Rosé de Provence est parfait pour les journées ensoleillées, avec des arômes délicats de fruits rouges.'
END
WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30);